name: Add profile credentials to ~/.aws/credentials
description: "adding profile to eb cli"
inputs:
  role-to-assume:
    description: "Role to Assume"
    required: true
outputs:
  ecr-registry:
    description: "Random number"
    value: ${{ steps.login-ecr.outputs.registry }}
runs:
  using: "composite"
  steps:
    - name: Configure AWS credentials from Test account
      uses: aws-actions/configure-aws-credentials@v4
      with:
        role-to-assume: ${{ inputs.who-to-greet }}
        aws-region: us-east-1
    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v2
    - name: Add profile credentials
      uses: ./.github/actions/add-profile-credentials
